package identity.domain.model;

public enum AuditAction {
    ACCOUNT_CREATED,
    CREDENTIALS_CHANGED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_REACTIVATED,
    ORGANIZATION_CREATED,
    REPRESENTATIVE_TRANSFERRED,
    ADMINISTRATOR_ASSIGNED,
    ADMINISTRATOR_REMOVED,
    EMPLOYEE_ADDED,
    EMPLOYEE_REMOVED,
    MEMBER_REMOVED,
    PLATFORM_AUTHORITY_GRANTED,
    PLATFORM_AUTHORITY_REVOKED,
    BOOTSTRAP_PLATFORM_AUTHORITY
}
