package com.traceability.core.application.authorization;

public enum CommandType {
    REGISTER_FUND,
    CLEAR_FUNDS_AS_GENESIS,
    CLEAR_FUNDS_FOR_PLEDGE,
    REGISTER_PHYSICAL_ASSET,
    REGISTER_PHYSICAL_ASSET_FROM_DONATION,
    SPLIT_PHYSICAL_ASSET,
    REVERSE_ALLOCATION_ADMINISTRATIVELY,
    REQUEST_ALLOCATION,
    CONFIRM_ALLOCATION,
    DELIVER_ASSET,
    /** D-ASSET (plan B6-c). */
    DISPATCH_PHYSICAL_ASSET,
    /** D-ASSET (plan B6-c). */
    RECEIVE_PHYSICAL_ASSET
}
